BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "bottazzi"
BBFILE_PATTERN_bottazzi = "^${LAYERDIR}/"
BBFILE_PRIORITY_bottazzi = "10"
LAYERSERIES_COMPAT_bottazzi = "scarthgap"

LAYERDEPENDS_bottazzi = "meta-tailscale"
